/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BerichtRouteImport } from './routes/bericht'
import { Route as ErgebnisRouteImport } from './routes/ergebnis'
import { Route as OrtRouteImport } from './routes/ort'
import { Route as PruefungRouteImport } from './routes/pruefung'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BerichtRoute = BerichtRouteImport.update({
  id: '/bericht',
  path: '/bericht',
  getParentRoute: () => rootRouteImport,
} as any)
const ErgebnisRoute = ErgebnisRouteImport.update({
  id: '/ergebnis',
  path: '/ergebnis',
  getParentRoute: () => rootRouteImport,
} as any)
const OrtRoute = OrtRouteImport.update({
  id: '/ort',
  path: '/ort',
  getParentRoute: () => rootRouteImport,
} as any)
const PruefungRoute = PruefungRouteImport.update({
  id: '/pruefung',
  path: '/pruefung',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bericht': typeof BerichtRoute
  '/ergebnis': typeof ErgebnisRoute
  '/ort': typeof OrtRoute
  '/pruefung': typeof PruefungRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bericht': typeof BerichtRoute
  '/ergebnis': typeof ErgebnisRoute
  '/ort': typeof OrtRoute
  '/pruefung': typeof PruefungRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bericht': typeof BerichtRoute
  '/ergebnis': typeof ErgebnisRoute
  '/ort': typeof OrtRoute
  '/pruefung': typeof PruefungRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bericht' | '/ergebnis' | '/ort' | '/pruefung'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bericht' | '/ergebnis' | '/ort' | '/pruefung'
  id: '__root__' | '/' | '/bericht' | '/ergebnis' | '/ort' | '/pruefung'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BerichtRoute: typeof BerichtRoute
  ErgebnisRoute: typeof ErgebnisRoute
  OrtRoute: typeof OrtRoute
  PruefungRoute: typeof PruefungRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bericht': {
      id: '/bericht'
      path: '/bericht'
      fullPath: '/bericht'
      preLoaderRoute: typeof BerichtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ergebnis': {
      id: '/ergebnis'
      path: '/ergebnis'
      fullPath: '/ergebnis'
      preLoaderRoute: typeof ErgebnisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ort': {
      id: '/ort'
      path: '/ort'
      fullPath: '/ort'
      preLoaderRoute: typeof OrtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pruefung': {
      id: '/pruefung'
      path: '/pruefung'
      fullPath: '/pruefung'
      preLoaderRoute: typeof PruefungRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BerichtRoute: BerichtRoute,
  ErgebnisRoute: ErgebnisRoute,
  OrtRoute: OrtRoute,
  PruefungRoute: PruefungRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
